import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#edf2f7",
  },
  screenDark: {
    backgroundColor: "#0b1220",
  },
  centered: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#edf2f7",
  },
  loginHero: {
    paddingTop: 60,
    paddingHorizontal: 22,
    paddingBottom: 12,
  },
  loginBrand: {
    fontSize: 30,
    fontWeight: "800",
    color: "#0f172a",
  },
  loginTag: {
    marginTop: 4,
    fontSize: 14,
    color: "#2563eb",
    fontWeight: "700",
  },
  loginHint: {
    marginTop: 6,
    fontSize: 12,
    color: "#64748b",
  },
  errorText: {
    marginTop: 2,
    marginBottom: 8,
    color: "#dc2626",
    fontSize: 12,
    fontWeight: "700",
  },
  loginCard: {
    marginHorizontal: 18,
    marginTop: 8,
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: "#dbe4f2",
    backgroundColor: "#f8f9fb",
  },
  loginCardDark: {
    borderColor: "#22314a",
    backgroundColor: "#111a2b",
  },
  headerWrap: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#d5e1ea",
    backgroundColor: "#edf2f8",
  },
  headerWrapDark: {
    borderBottomColor: "#1f2a3d",
    backgroundColor: "#111a2b",
  },
  headerKicker: {
    fontSize: 11,
    color: "#64748b",
    fontWeight: "600",
  },
  headerKickerDark: {
    color: "#8aa0be",
  },
  headerTitle: {
    marginTop: 2,
    fontSize: 19,
    fontWeight: "800",
    color: "#0f172a",
  },
  headerTitleDark: {
    color: "#e2e8f0",
  },
  refreshGhost: {
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: "#f0f4f9",
  },
  refreshGhostDark: {
    borderColor: "#22314a",
    backgroundColor: "#0d1826",
  },
  refreshGhostText: {
    color: "#334155",
    fontSize: 12,
    fontWeight: "700",
  },
  refreshGhostTextDark: {
    color: "#8aa0be",
  },
  content: {
    flex: 1,
    paddingHorizontal: 12,
    paddingTop: 12,
    backgroundColor: "#edf2f7",
  },
  contentDark: {
    backgroundColor: "#0b1220",
  },
  gradientCardWarm: {
    borderRadius: 16,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#bfdbfe",
    backgroundColor: "#eff6ff",
  },
  gradientCardWarmDark: {
    borderColor: "#1e3a5f",
    backgroundColor: "#0f1f35",
  },
  gradientCard: {
    borderRadius: 16,
    padding: 14,
    backgroundColor: "#0f172a",
    marginBottom: 12,
  },
  gradientCardDark: {
    backgroundColor: "#14213a",
  },
  gradientCardTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: "#f8fafc",
  },
  gradientCardText: {
    marginTop: 4,
    fontSize: 12,
    color: "#cbd5e1",
  },
  card: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#dce4ef",
    backgroundColor: "#f8f9fb",
    padding: 12,
    marginBottom: 10,
    shadowColor: "#0f172a",
    shadowOpacity: 0.05,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  cardDark: {
    borderColor: "#22314a",
    backgroundColor: "#111a2b",
    shadowOpacity: 0,
    elevation: 0,
  },
  cardSelected: {
    borderColor: "#3b82f6",
    backgroundColor: "#eff6ff",
  },
  unreadCard: {
    borderColor: "#94a3b8",
    backgroundColor: "#f8fafc",
  },
  unreadCardDark: {
    borderColor: "#334155",
    backgroundColor: "#131e2f",
  },
  cardTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: "#0f172a",
    marginBottom: 4,
  },
  cardTitleDark: {
    color: "#e2e8f0",
  },
  cardLine: {
    fontSize: 13,
    color: "#334155",
    marginBottom: 2,
  },
  cardLineDark: {
    color: "#cbd5e1",
  },
  meta: {
    marginTop: 6,
    fontSize: 11,
    color: "#64748b",
  },
  listItemBlock: {
    borderTopWidth: 1,
    borderTopColor: "#eef2f7",
    paddingTop: 8,
    marginTop: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: "#c8d5e2",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    marginBottom: 8,
    backgroundColor: "#f4f7fb",
  },
  inputDark: {
    borderColor: "#334155",
    backgroundColor: "#0f172a",
    color: "#e2e8f0",
  },
  textArea: {
    minHeight: 80,
    textAlignVertical: "top",
  },
  primaryBtn: {
    borderRadius: 10,
    backgroundColor: "#0284c7",
    paddingVertical: 11,
    alignItems: "center",
  },
  primaryBtnDark: {
    backgroundColor: "#0ea5e9",
  },
  primaryBtnText: {
    fontSize: 14,
    color: "#ffffff",
    fontWeight: "700",
  },
  secondaryBtn: {
    borderRadius: 10,
    backgroundColor: "#0f172a",
    paddingVertical: 11,
    alignItems: "center",
    marginBottom: 8,
  },
  secondaryBtnText: {
    fontSize: 13,
    color: "#ffffff",
    fontWeight: "700",
  },
  preview: {
    width: "100%",
    height: 170,
    borderRadius: 10,
    marginBottom: 8,
  },
  sectionHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
    paddingHorizontal: 2,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#0f172a",
  },
  sectionTitleDark: {
    color: "#e2e8f0",
  },
  linkText: {
    fontSize: 12,
    color: "#2563eb",
    fontWeight: "600",
  },
  linkTextDark: {
    color: "#7dd3fc",
  },
  emptyText: {
    textAlign: "center",
    color: "#64748b",
    marginTop: 24,
    fontSize: 13,
  },
  emptyTextDark: {
    color: "#475569",
  },
  quickGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  quickBtn: {
    width: "48%",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#d8e1ed",
    backgroundColor: "#f4f7fb",
    paddingVertical: 10,
    alignItems: "center",
  },
  quickBtnDark: {
    borderColor: "#22314a",
    backgroundColor: "#0d1826",
  },
  quickBtnText: {
    fontSize: 12,
    color: "#334155",
    fontWeight: "700",
  },
  quickBtnTextDark: {
    color: "#94a3b8",
  },
  stepRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginBottom: 8,
  },
  stepBtn: {
    borderWidth: 1,
    borderColor: "#c8d5e2",
    borderRadius: 999,
    paddingVertical: 7,
    paddingHorizontal: 10,
    backgroundColor: "#f4f7fb",
  },
  stepBtnDark: {
    borderColor: "#22314a",
    backgroundColor: "#0d1826",
  },
  stepBtnActive: {
    borderColor: "#0284c7",
    backgroundColor: "#e0f2fe",
  },
  stepText: {
    fontSize: 11,
    color: "#334155",
    fontWeight: "700",
  },
  stepTextDark: {
    color: "#94a3b8",
  },
  stepTextActive: {
    color: "#0c4a6e",
  },
  tabBar: {
    flexDirection: "row",
    borderTopWidth: 1,
    borderTopColor: "#d8e1ed",
    backgroundColor: "#edf2f8",
    paddingHorizontal: 10,
    paddingVertical: 10,
    gap: 6,
  },
  tabBarDark: {
    borderTopColor: "#1f2a3d",
    backgroundColor: "#111a2b",
  },
  tabButton: {
    flex: 1,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    paddingVertical: 6,
    alignItems: "center",
  },
  tabButtonDark: {
    borderColor: "#334155",
    backgroundColor: "#0f172a",
  },
  tabButtonActive: {
    borderColor: "#38bdf8",
    backgroundColor: "#e0f2fe",
  },
  tabButtonActiveDark: {
    borderColor: "#38bdf8",
    backgroundColor: "#082f49",
  },
  tabIcon: {
    fontSize: 12,
    color: "#64748b",
    fontWeight: "700",
    marginBottom: 2,
  },
  tabIconDark: {
    color: "#8aa0be",
  },
  tabIconActive: {
    color: "#0c4a6e",
  },
  tabLabel: {
    fontSize: 9,
    color: "#334155",
    fontWeight: "800",
  },
  tabLabelDark: {
    color: "#cbd5e1",
  },
  tabLabelActive: {
    color: "#0c4a6e",
  },
  tabLabelActiveDark: {
    color: "#7dd3fc",
  },
  logoutBtn: {
    marginTop: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#ef4444",
    paddingVertical: 11,
    alignItems: "center",
    backgroundColor: "#fff1f2",
  },
  logoutBtnDark: {
    borderColor: "#f43f5e",
    backgroundColor: "#3f1020",
  },
  logoutText: {
    color: "#dc2626",
    fontSize: 13,
    fontWeight: "800",
  },
  inlineDangerBtn: {
    marginTop: 8,
    alignSelf: "flex-start",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#fecaca",
    backgroundColor: "#fff1f2",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  inlineDangerBtnText: {
    color: "#b91c1c",
    fontSize: 12,
    fontWeight: "700",
  },
  rowBetween: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  rowInline: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  brandBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderWidth: 1,
    borderColor: "#bae6fd",
    backgroundColor: "#e0f2fe",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginRight: 8,
  },
  brandBadgeDark: {
    borderColor: "#075985",
    backgroundColor: "#082f49",
  },
  brandBadgeText: {
    fontSize: 11,
    fontWeight: "800",
    color: "#0c4a6e",
  },
  brandBadgeTextDark: {
    color: "#bae6fd",
  },
  tabBadge: {
    position: "absolute",
    top: 4,
    right: 8,
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    borderRadius: 999,
    backgroundColor: "#dc2626",
    alignItems: "center",
    justifyContent: "center",
  },
  tabBadgeDark: {
    backgroundColor: "#f43f5e",
  },
  tabBadgeText: {
    color: "#ffffff",
    fontSize: 10,
    fontWeight: "800",
  },
  toastWrap: {
    position: "absolute",
    top: 72,
    left: 12,
    right: 12,
    zIndex: 20,
  },
  toastCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#dce4ef",
    backgroundColor: "#f8f9fb",
    paddingHorizontal: 14,
    paddingVertical: 10,
    shadowColor: "#0f172a",
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  toastCardDark: {
    borderColor: "#1f2a3d",
    backgroundColor: "#111a2b",
    shadowOpacity: 0,
    elevation: 0,
  },
  toastTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#0f172a",
  },
  toastTitleDark: {
    color: "#e2e8f0",
  },
  toastMessage: {
    marginTop: 3,
    fontSize: 12,
    color: "#475569",
  },
  toastMessageDark: {
    color: "#94a3b8",
  },
});
